export const CALENDAR_WEEK_ROWS = 6;
export const CALENDAR_DAYS_PER_WEEK = 7;

const CALENDAR_CELL_MIN_HEIGHT = 48;
const CALENDAR_ROW_PADDING_VERTICAL = 2;

export const CALENDAR_ROW_HEIGHT = CALENDAR_CELL_MIN_HEIGHT + CALENDAR_ROW_PADDING_VERTICAL * 2;
export const CALENDAR_ROW_PADDING = CALENDAR_ROW_PADDING_VERTICAL;
export const CALENDAR_DAY_CELL_MIN_HEIGHT = CALENDAR_CELL_MIN_HEIGHT;
