import { selectStaticCopy } from "../i18n/staticCopy";

export const AnnualReportCopy = selectStaticCopy({
  en: {
    confirmTitle: "Download report?",
    customRangeOption: "Choose custom range",
    customRangeTitle: "Choose a period.",
    customRangeInvalidMessage: "Start date cannot be later than end date.",
    downloadAction: "Download",
    firstToLastOption: "First to last entry date",
    headerAccessibilityLabel: "Download report",
    authorSummarySheetName: "Member Summary",
    categorySummarySheetName: "Category Summary",
    chartSheetName: "Charts",
    ledgerSheetName: "Ledger",
    monthlySummarySheetName: "Monthly Summary",
    noEntriesMessage: "There are no transactions yet, so a report cannot be created.",
    optionTitle: "Choose report range.",
    rangeEndLabel: "End Date",
    rangeStartLabel: "Start Date",
    summarySheetName: "Summary",
    errorMessage: "Could not create the report.",
    successMessage: "Report is ready.",
    chartTitleSuffix: "Charts",
    confirmMessageSuffix: "report will be downloaded.",
    selectedYearOptionSuffix: " full year",
    ledgerHeaders: [
      "Date",
      "Month",
      "Type",
      "Description",
      "Category",
      "Income",
      "Expense",
      "Balance",
      "Target Member",
      "Author",
      "Memo",
      "Receipts",
      "Installment",
      "Created At",
      "Updated At",
      "Entry ID",
    ],
    monthlySummaryHeaders: ["Month", "Income", "Expense", "Balance", "Count"],
    expenseCategoryHeaders: ["Expense Category", "Expense", "Share", "Count"],
    incomeCategoryHeaders: ["Income Category", "Income", "Share", "Count"],
    memberSummaryHeaders: ["Member", "Income", "Expense", "Balance", "Count"],
    summaryRows: {
      balance: "Period Balance",
      entryCount: "Entry Count",
      expense: "Total Expense",
      generatedAt: "Generated At",
      income: "Total Income",
      ledger: "Ledger",
      note: "Note",
      noteValue: "Reference material for organizing and sharing group ledgers.",
      period: "Period",
      topExpenseCategory: "Top Expense Category",
      topIncomeCategory: "Top Income Category",
    },
    typeLabels: {
      expense: "Expense",
      income: "Income",
    },
    emptyCategoryLabels: {
      expense: "No expenses",
      income: "No income",
    },
    chartTitles: {
      expenseCategory: "Expense by Category",
      incomeCategory: "Income by Category",
      member: "Income and Expense by Member",
      monthly: "Monthly Income and Expense",
    },
  },
  ko: {
    confirmTitle: "보고서를 다운로드할까요?",
    customRangeOption: "날짜 선택하기",
    customRangeTitle: "기간을 선택해 주세요.",
    customRangeInvalidMessage: "시작 날짜가 종료 날짜보다 늦을 수 없습니다.",
    downloadAction: "다운로드",
    firstToLastOption: "처음 등록일부터 마지막까지",
    headerAccessibilityLabel: "보고서 다운로드",
    authorSummarySheetName: "담당자별 집계",
    categorySummarySheetName: "분류별 집계",
    chartSheetName: "차트",
    ledgerSheetName: "원장",
    monthlySummarySheetName: "월별 집계",
    noEntriesMessage: "아직 거래가 없어 보고서를 만들 수 없습니다.",
    optionTitle: "보고서 범위를 선택해 주세요.",
    rangeEndLabel: "종료 날짜",
    rangeStartLabel: "시작 날짜",
    summarySheetName: "요약",
    errorMessage: "보고서를 만들지 못했습니다.",
    successMessage: "보고서를 준비했습니다.",
    chartTitleSuffix: "차트",
    confirmMessageSuffix: "보고서를 다운로드합니다.",
    selectedYearOptionSuffix: "년 한 해",
    ledgerHeaders: [
      "거래일",
      "연월",
      "유형",
      "내용",
      "분류",
      "수입",
      "지출",
      "수지",
      "담당자",
      "작성자",
      "메모",
      "증빙수",
      "분할",
      "등록일",
      "수정일",
      "거래ID",
    ],
    monthlySummaryHeaders: ["월", "수입", "지출", "수지", "건수"],
    expenseCategoryHeaders: ["지출 분류", "지출", "비중", "건수"],
    incomeCategoryHeaders: ["수입 분류", "수입", "비중", "건수"],
    memberSummaryHeaders: ["담당자", "수입", "지출", "수지", "건수"],
    summaryRows: {
      balance: "기간 수지",
      entryCount: "기록 건수",
      expense: "총지출",
      generatedAt: "생성일",
      income: "총수입",
      ledger: "가계부",
      note: "안내",
      noteValue: "모임 장부 정리와 공유를 위한 참고용 자료입니다.",
      period: "기간",
      topExpenseCategory: "주요 지출 분류",
      topIncomeCategory: "주요 수입 분류",
    },
    typeLabels: {
      expense: "지출",
      income: "수입",
    },
    emptyCategoryLabels: {
      expense: "지출 없음",
      income: "수입 없음",
    },
    chartTitles: {
      expenseCategory: "지출 분류별 금액",
      incomeCategory: "수입 분류별 금액",
      member: "담당자별 수입과 지출",
      monthly: "월별 수입과 지출",
    },
  },
} as const);

export type AnnualReportRangeMode = "custom-range" | "first-to-last" | "selected-year";

export const AnnualReportUi = {
  rangeFieldBorderWidth: 1,
  rangeFieldGap: 8,
  headerIconSize: 14,
  rangeFieldPaddingHorizontal: 10,
  rangeFieldPaddingVertical: 8,
  rangePickerGap: 10,
} as const;

export function buildAnnualReportConfirmMessage(bookName: string): string {
  return `${bookName} ${AnnualReportCopy.confirmMessageSuffix}`;
}

export function buildAnnualReportOptionDescription(
  mode: AnnualReportRangeMode,
  optionLabel: string,
  periodLabel: string,
): string {
  return `${optionLabel}\n${periodLabel}`;
}

export function buildSelectedYearOptionLabel(year: number): string {
  return `${year}${AnnualReportCopy.selectedYearOptionSuffix}`;
}
