export const CATEGORY_GRID_COLUMNS = 3;
export const CATEGORY_GRID_GAP = 6;
export const CATEGORY_DRAG_LONG_PRESS_MS = 180;
export const CATEGORY_DRAG_START_THRESHOLD = 8;
export const CATEGORY_DRAG_ANIMATION_MS = 140;
export const CATEGORY_DRAG_SCALE = 1.04;
