export const CATEGORY_GRID_GAP = 6;
export const CATEGORY_GRID_MIN_CELL_SIZE = 58;
export const CATEGORY_GRID_MIN_COLUMNS = 4;
export const CATEGORY_DELETE_BUTTON_INSET = 4;
export const CATEGORY_DELETE_BUTTON_SIZE = 18;
export const CATEGORY_DELETE_ICON_SIZE = 11;
export const CATEGORY_ICON_SIZE = 16;
export const CATEGORY_ICON_LABEL_GAP = 4;
export const CATEGORY_ITEM_PADDING_HORIZONTAL = 4;
export const CATEGORY_ITEM_PADDING_VERTICAL = 6;
export const CATEGORY_DRAG_LONG_PRESS_MS = 180;
export const CATEGORY_DRAG_START_THRESHOLD = 8;
export const CATEGORY_DRAG_ANIMATION_MS = 140;
export const CATEGORY_DRAG_SCALE = 1.04;
export const CATEGORY_DELETE_DROP_ZONE_SIZE = 64;
export const CATEGORY_DELETE_DROP_ZONE_ICON_SIZE = 24;
export const CATEGORY_INLINE_CREATOR_ICON_SIZE = 18;
export const CATEGORY_INLINE_ICON_PICKER_HEIGHT = 112;
export const CATEGORY_INLINE_ICON_PICKER_COLUMNS = 3;
export const CATEGORY_INLINE_ICON_PICKER_ITEM_SIZE = 34;
export const CATEGORY_INLINE_ICON_PICKER_GAP = 8;
export const CATEGORY_INLINE_ICON_PICKER_ARROW_SIZE = 10;
export const CATEGORY_INLINE_ICON_PICKER_PADDING = 10;
export const CATEGORY_INLINE_ICON_PICKER_ANCHOR_GAP = -24;
export const CATEGORY_INLINE_ICON_PICKER_WIDTH =
  CATEGORY_INLINE_ICON_PICKER_PADDING * 2 +
  CATEGORY_INLINE_ICON_PICKER_COLUMNS * CATEGORY_INLINE_ICON_PICKER_ITEM_SIZE +
  (CATEGORY_INLINE_ICON_PICKER_COLUMNS - 1) * CATEGORY_INLINE_ICON_PICKER_GAP;
