export const EmailAuthCopy = {
  accountProviderValue: "이메일 인증",
  confirmationStatus: "가입이 완료되었습니다. 이메일 인증 후 로그인해 주세요.",
  emailLabel: "이메일",
  emailPlaceholder: "you@example.com",
  helperSignIn: "이메일과 비밀번호로 바로 로그인할 수 있습니다.",
  helperSignUp: "가입 시 기기에서 비밀번호 추천을 사용할 수 있습니다.",
  modeSignIn: "로그인",
  modeSignUp: "가입",
  passwordConfirmLabel: "비밀번호 확인",
  passwordConfirmPlaceholder: "비밀번호를 한 번 더 입력하세요",
  passwordLabel: "비밀번호",
  passwordPlaceholder: "비밀번호를 입력하세요",
  secureNote: "이메일로 안전하게 시작",
  signUpNotice: "가입 후에는 이메일 인증을 완료해야 로그인할 수 있습니다.",
  signInAction: "로그인",
  signUpAction: "가입하기",
  subtitle: "로그인하면 내 기록과 공유 가계부를 안전하게 사용할 수 있습니다.",
  supportLabel: "수입·지출 기록, 공유 가계부, 월간 차트",
  title: "이메일로 로그인",
} as const;
