export const EmailAuthCopy = {
  accountProviderValue: "이메일",
  supportLabel: "지출 기록, 공유 가계부, 월간 차트를 안전하게 이어서 관리",
  signIn: {
    title: "이메일로 안전하게 로그인",
    emailLabel: "이메일",
    emailPlaceholder: "이메일을 입력해 주세요",
    passwordLabel: "비밀번호",
    passwordPlaceholder: "비밀번호를 입력해 주세요",
    submitAction: "로그인",
    openSignUpAction: "이메일로 가입하기",
  },
  signUp: {
    backAction: "로그인으로 돌아가기",
    title: "이메일로 가입하기",
    subtitle: "비밀번호를 만든 뒤, 이메일로 받은 인증 코드를 입력해야 가입이 완료돼요.",
    emailLabel: "이메일",
    emailPlaceholder: "이메일을 입력해 주세요",
    passwordLabel: "비밀번호",
    passwordPlaceholder: "새 비밀번호를 입력해 주세요",
    passwordConfirmLabel: "비밀번호 확인",
    passwordConfirmPlaceholder: "비밀번호를 다시 입력해 주세요",
    requestOtpAction: "인증 코드 받기",
    otpTitle: "이메일 인증 코드 입력",
    otpSubtitle: "가입 메일에 도착한 6자리 코드를 입력해 가입을 마무리하세요.",
    otpLabel: "인증 코드",
    otpPlaceholder: "6자리 코드 입력",
    verifyOtpAction: "가입 완료",
    resendOtpAction: "코드 다시 받기",
    editCredentialsAction: "가입 정보 수정",
    otpRequestedStatus: "인증 코드를 보냈습니다. 메일함을 확인해 주세요.",
    otpResentStatus: "인증 코드를 다시 보냈습니다.",
    otpResendCooldownStatus: "보안을 위해 인증 코드는 잠시 후 다시 요청할 수 있어요.",
  },
} as const;
