import { selectStaticCopy } from "../i18n/staticCopy";

export const EmailAuthCopy = selectStaticCopy({
  en: {
    accountProviderValue: "Email",
    legalConsentNotice: "By signing in, you agree to the Terms of Use and Privacy Policy.",
    legalLinkError: "Could not open the terms link.",
    supportLabel: "Keep managing entries, shared ledgers, and charts securely",
    signIn: {
      title: "Welcome back!",
      appleAgreementTitle: "Continue with Apple",
      emailLabel: "Email",
      emailPlaceholder: "Enter your email",
      emailTitle: "Sign in with Email",
      googleAgreementTitle: "Continue with Google",
      passwordLabel: "Password",
      passwordPlaceholder: "Enter your password",
      submitAction: "Sign In",
      forgotPasswordAction: "Forgot password?",
      openSignUpAction: "Create Account with Email",
    },
    passwordReset: {
      backToSignInAction: "Back to sign in",
      confirmPasswordLabel: "Confirm Password",
      confirmPasswordPlaceholder: "Re-enter your new password",
      errorFallback: "Could not reset your password. Please try again.",
      newPasswordLabel: "New Password",
      newPasswordPlaceholder: "Enter a new password",
      requestAction: "Send Reset Email",
      requestSuccess: "Password reset email sent. Check your inbox.",
      requestSubtitle: "Enter your email and open the reset link from your inbox.",
      requestTitle: "Reset Password",
      updateAction: "Update Password",
      updateSubtitle: "Enter a new password to finish resetting your account.",
      updateSuccess: "Password updated.",
      updateTitle: "Create New Password",
    },
    signUp: {
      agreementAllLabel: "Agree to all",
      agreementNextAction: "Next",
      agreementPrivacyLabel: "I agree to the collection and use of personal information.",
      agreementRequiredPrefix: "Required",
      agreementTermsLabel: "I agree to the Terms of Use.",
      agreementViewAction: "View",
      backAction: "Back to sign in",
      stepAgreementLabel: "Terms",
      stepCredentialsLabel: "Account",
      stepOtpLabel: "Verify",
      title: "Create Account with Email",
      subtitle: "After creating a password, enter the verification code sent to your email.",
      emailLabel: "Email",
      emailPlaceholder: "Enter your email",
      passwordLabel: "Password",
      passwordPlaceholder: "Enter a new password",
      passwordConfirmLabel: "Confirm Password",
      passwordConfirmPlaceholder: "Re-enter your password",
      requestOtpAction: "Get Verification Code",
      requestOtpError: "Could not start email verification. Please try again.",
      otpTitle: "Enter Email Verification Code",
      otpSubtitle: "Enter the 6-digit code from your signup email to finish creating your account.",
      otpLabel: "Verification Code",
      otpPlaceholder: "Enter 6-digit code",
      verifyOtpAction: "Finish Sign Up",
      resendOtpAction: "Resend Code",
      editCredentialsAction: "Edit Sign-up Info",
      otpRequestedStatus: "Verification code sent. Check your inbox.",
      otpResentStatus: "Verification code resent.",
      otpResendCooldownStatus: "For security, you can request another code shortly.",
    },
  },
  ko: {
    accountProviderValue: "이메일",
    legalConsentNotice: "로그인하면 이용약관 및 개인정보 처리방침에 동의한 것으로 간주됩니다.",
    legalLinkError: "약관 링크를 열지 못했어요.",
    supportLabel: "입출금 기록, 공유 가계부, 차트를 안전하게 이어서 관리",
    signIn: {
      title: "반가워요!",
      appleAgreementTitle: "APPLE로 계속하기",
      emailLabel: "이메일",
      emailPlaceholder: "이메일을 입력해 주세요",
      emailTitle: "이메일로 로그인",
      googleAgreementTitle: "GOOGLE로 계속하기",
      passwordLabel: "비밀번호",
      passwordPlaceholder: "비밀번호를 입력해 주세요",
      submitAction: "로그인",
      forgotPasswordAction: "비밀번호를 잊으셨나요?",
      openSignUpAction: "이메일로 가입하기",
    },
    passwordReset: {
      backToSignInAction: "로그인으로 돌아가기",
      confirmPasswordLabel: "비밀번호 확인",
      confirmPasswordPlaceholder: "새 비밀번호를 다시 입력해 주세요",
      errorFallback: "비밀번호를 재설정하지 못했어요. 다시 시도해 주세요.",
      newPasswordLabel: "새 비밀번호",
      newPasswordPlaceholder: "새 비밀번호를 입력해 주세요",
      requestAction: "재설정 메일 보내기",
      requestSuccess: "비밀번호 재설정 메일을 보냈습니다. 메일함을 확인해 주세요.",
      requestSubtitle: "가입한 이메일을 입력하고 메일함의 재설정 링크를 열어 주세요.",
      requestTitle: "비밀번호 재설정",
      updateAction: "비밀번호 변경",
      updateSubtitle: "새 비밀번호를 입력하면 재설정이 완료돼요.",
      updateSuccess: "비밀번호가 변경됐어요.",
      updateTitle: "새 비밀번호 만들기",
    },
    signUp: {
      agreementAllLabel: "전체 동의",
      agreementNextAction: "다음",
      agreementPrivacyLabel: "개인정보 수집·이용에 동의합니다.",
      agreementRequiredPrefix: "필수",
      agreementTermsLabel: "이용약관에 동의합니다.",
      agreementViewAction: "보기",
      backAction: "로그인으로 돌아가기",
      stepAgreementLabel: "약관",
      stepCredentialsLabel: "계정",
      stepOtpLabel: "인증",
      title: "이메일로 가입하기",
      subtitle: "비밀번호를 만든 뒤, 이메일로 받은 인증 코드를 입력해야 가입이 완료돼요.",
      emailLabel: "이메일",
      emailPlaceholder: "이메일을 입력해 주세요",
      passwordLabel: "비밀번호",
      passwordPlaceholder: "새 비밀번호를 입력해 주세요",
      passwordConfirmLabel: "비밀번호 확인",
      passwordConfirmPlaceholder: "비밀번호를 다시 입력해 주세요",
      requestOtpAction: "인증 코드 받기",
      requestOtpError: "이메일 인증을 시작하지 못했어요. 다시 시도해 주세요.",
      otpTitle: "이메일 인증 코드 입력",
      otpSubtitle: "가입 메일에 도착한 6자리 코드를 입력해 가입을 마무리하세요.",
      otpLabel: "인증 코드",
      otpPlaceholder: "6자리 코드 입력",
      verifyOtpAction: "가입 완료",
      resendOtpAction: "코드 다시 받기",
      editCredentialsAction: "가입 정보 수정",
      otpRequestedStatus: "인증 코드를 보냈습니다. 메일함을 확인해 주세요.",
      otpResentStatus: "인증 코드를 다시 보냈습니다.",
      otpResendCooldownStatus: "보안을 위해 인증 코드는 잠시 후 다시 요청할 수 있어요.",
    },
  },
} as const);

export const EmailSignUpAgreementUi = {
  actionGroupGap: 8,
  actionGroupPaddingTop: 4,
  cardGap: 12,
  checkBoxSize: 22,
  checkIconSize: 16,
  checkBoxBorderRadius: 4,
  checkBoxBorderWidth: 1,
  dividerHeight: 1,
  labelFontSize: 14,
  labelLineHeight: 20,
  rowGap: 10,
} as const;

export const EmailSignUpStepUi = {
  connectorHeight: 1,
  dotBorderWidth: 1,
  dotSize: 16,
  labelFontSize: 11,
  labelLineHeight: 16,
  rowGap: 8,
  stepGap: 6,
} as const;

export const EmailSignUpOtpUi = {
  actionGroupGap: 8,
  secondaryActionGap: 8,
} as const;
