
export const EntryRegistrationCopy = {
    amountRequiredError: "금액을 입력해 주세요.",
    categoryLabel: "분류",
    categoryRequiredError: "분류를 선택해 주세요.",
    contentLabel: "내용",
    contentPlaceholder: "내용 입력",
    contentRequiredError: "내용을 입력해 주세요.",
    dailyFirstEntryAdNoticeMessage: "매일 첫 등록 시 한 번만 진행됩니다.",
    dailyFirstEntryAdNoticeTitle: "저장 전 광고가 표시됩니다",
    dailyFirstEntryAdUnavailableError: "광고를 불러오지 못했어요. 잠시 후 다시 등록해 주세요.",
    dailyFirstEntryRewardRequiredError: "광고 시청을 완료해 주세요. (매일 최초 1회)",
    installmentPickerTitle: "할부 선택",
    installmentSettleAction: "할부 정리",
    installmentSettleConfirmMessage: "할부 금액을 이번 달에 모두 결제할까요?",
    installmentSettleSuccess: "할부를 정리했어요.",
    installmentSettleUnavailable: "정리할 할부가 없어요.",
    noteLabel: "메모",
    saveCreateSuccess: "내역을 등록했어요.",
    saveError: "기록 저장에 실패했어요.",
    saveMigrationError: "DB 마이그레이션 적용이 필요해요.",
    saveUpdateSuccess: "내역을 수정했어요.",
    targetMemberLabel: "대상 구성원",
  } as const;
