export const EntryRegistrationCopy = {
  addEntryAction: "목록에 추가",
  amountRequiredError: "금액을 입력해 주세요.",
  categoryLabel: "분류",
  categoryRequiredError: "분류를 선택해 주세요.",
  contentLabel: "내용",
  contentPlaceholder: "내용 입력",
  contentRequiredError: "내용을 입력해 주세요.",
  installmentPickerTitle: "할부 선택",
  installmentSettleAction: "남은 할부 정리",
  installmentSettleConfirmMessage: "남은 할부를 이번 달에 모두 결제했나요?",
  installmentSettleSuccess: "남은 할부를 정리했어요.",
  installmentSettleUnavailable: "정리할 남은 할부가 없어요.",
  saveError: "기록 저장에 실패했어요.",
  saveMigrationError: "DB 마이그레이션 적용이 필요해요.",
  noteLabel: "메모",
  queuedEntriesTitle: "추가 등록 예정",
  queuedEntriesCountLabel: (count: number) => `추가 등록 예정 ${count}건`,
  removeQueuedEntryAction: "삭제",
  summarySeparator: " · ",
} as const;
