import { selectStaticCopy } from "../i18n/staticCopy";

export const LedgerBookManagementCopy = selectStaticCopy({
  en: {
    createAction: "Add Ledger",
    createError:
      "Could not create a ledger. If you just joined plus, restore purchases and try again.",
    createConfirmMessageSuffix: "Add this ledger?",
    createConfirmTitle: "Confirm Add Ledger",
    createFreePlanLimitReached: "Adding another ledger requires Alttle plus.",
    createLimitReached: "You have used all available ledgers.",
    createNamePromptMessage: "Enter a new ledger name.",
    createNamePromptTitle: "Create this ledger?",
    createNameRequired: "Enter a ledger name.",
    createNamePlaceholder: "New ledger name",
    createSuccess: "Switched to the new ledger.",
    currentBadge: "Current",
    emptyList: "No ledgers available.",
    listTitle: "My Ledgers",
    ownerBadge: "Owner",
    sharedBadge: "Shared",
    activeStateLabel: "Current",
    switchActionAccessibilityLabel: "Switch ledger",
    switchError: "Could not switch ledgers.",
    switchSuccess: "Ledger switched.",
  },
  ko: {
    createAction: "가계부 추가",
    createError: "가계부를 만들지 못했어요. 구독을 복원한 뒤 다시 시도해주세요.",
    createConfirmMessageSuffix: "가계부를 추가할까요?",
    createConfirmTitle: "가계부 추가 확인",
    createFreePlanLimitReached: "가계부를 추가하려면 알뜰 plus를 구독해 주세요.",
    createLimitReached: "사용 가능한 가계부 개수를 모두 사용했어요.",
    createNamePromptMessage: "새 가계부 이름을 입력해 주세요.",
    createNamePromptTitle: "정말로 가계부를 생성할까요?",
    createNameRequired: "가계부 이름을 입력해 주세요.",
    createNamePlaceholder: "새 가계부 이름",
    createSuccess: "새 가계부로 전환했어요.",
    currentBadge: "사용 중",
    emptyList: "사용 가능한 가계부가 없어요.",
    listTitle: "내 가계부",
    ownerBadge: "소유",
    sharedBadge: "공유",
    activeStateLabel: "사용 중",
    switchActionAccessibilityLabel: "가계부 전환",
    switchError: "가계부를 전환하지 못했어요.",
    switchSuccess: "가계부를 전환했어요.",
  },
} as const);
