
export const MonthlyInsightChartCopy = {
    breakdownCategoryLabel: "카테고리별",
    breakdownMemberLabel: "구성원별",
    categoryEmpty: "지출 내역이 없어 카테고리 차트를 표시하지 않아요.",
    categoryTitle: "카테고리별 지출",
    filteredEmpty: "표시 중인 항목이 없어 차트를 표시하지 않아요.",
    hiddenItemAccessibilitySuffix: "숨김 상태",
    visibleItemAccessibilitySuffix: "표시 중",
    expenseLabel: "지출",
    incomeCategoryEmpty: "수입 내역이 없어 카테고리 차트를 표시하지 않아요.",
    incomeCategoryTitle: "카테고리별 수입",
    incomeLabel: "수입",
    incomeMemberEmpty: "수입 내역이 없어 구성원 차트를 표시하지 않아요.",
    incomeMemberTitle: "구성원별 수입",
    memberEmpty: "지출 내역이 없어 구성원 차트를 표시하지 않아요.",
    memberTitle: "구성원별 지출",
    previousComparisonTitle: "전월 비교",
    periodTrendTitle: "최근 6개 기간 수입/지출",
    totalExpenseLabel: "총지출",
    totalIncomeLabel: "총수입",
    trendTitle: "최근 6개월 수입/지출",
  } as const;

export const MonthlyInsightChartLayout = {
  donutLegendDotSize: 8,
  donutLegendGap: 2,
  donutLegendInactiveOpacity: 0.6,
  donutLegendRowPaddingHorizontal: 2,
  donutLegendRowMinHeight: 26,
  donutSize: 152,
  donutStrokeWidth: 24,
  minVisibleBarHeight: 3,
  segmentIndicatorHeight: 2,
  trendBarHeight: 104,
  trendYAxisGap: 6,
  trendYAxisLabelCount: 3,
} as const;

export const MonthlyComparisonLayout = {
  amountFontSize: 22,
  amountLineHeight: 28,
  bodyGap: 5,
  dividerHeight: 1,
  headerGap: 8,
  labelFontSize: 11,
  labelLineHeight: 15,
  listGap: 0,
  previousFontSize: 11,
  previousLineHeight: 15,
  railRadius: 999,
  railWidth: 4,
  rowGap: 10,
  rowPaddingHorizontal: 2,
  rowPaddingVertical: 10,
  sentenceFontSize: 13,
  sentenceLineHeight: 19,
} as const;
